project:
  type: website
  
website:
  title: "AI Salary Disparities"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: introduction.qmd
        text: Introduction
      - href: literature_review.qmd
        text: Literature Review
      - href: analysis.qmd
        text: Analysis
      - href: ai_vs_traditional.qmd
        text: AI vs Traditional
      - href: about.qmd
        text: About
      - href: data_analysis.qmd
        text: "Data Analysis"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



