---
title: "Introduction"
bibliography: references.bib
csl: csl/econometrica.csl
format:
  html:
    toc: true
---

Artificial intelligence (AI) is changing how people work in many industries. It helps companies do tasks faster and make better decisions, but it also affects how much people get paid. Some jobs, especially those that involve technology or data, are becoming more valuable and may pay more. Other jobs may not see the same increase. This makes it important to understand who is benefiting the most from AI and how salaries are changing across different fields.

This topic matters because of emerging trends of companies starting to use AI, which is increasing the demand for certain skills. As a result, people with those skills may earn higher salaries, while others may not see as much growth. In this analysis, it is expected that jobs related to technology, data, and finance will see higher pay increases, while more routine jobs may not. Overall, AI is likely creating bigger differences in pay between different types of work @brynjolfsson2014.

## References